### ISSUE TITLE
Support for implicit authentication

### ISSUE THREAD

**Issue by dsvensson** [HuiiBuh/AsyncSpotify#23]
Implicit authentication allows for higher request throttling limit.

https://developer.spotify.com/documentation/general/guides/authorization-guide/#client-credentials-flow

Set `grant_type` to `client_credentials`, skip `scopes`, and `redirect_uri` requirement in preferences.

**Comment by HuiiBuh** [comment]
Hey I just added it. 
If you have any other issues please report them to me

**Comment by HuiiBuh** [comment]
See here for the documentation.
