### ISSUE TITLE
AuthorizationCodeFlow requires scopes when empty scopes are valid.

### ISSUE THREAD

**Issue by describe19** [HuiiBuh/AsyncSpotify#31]
I encountered this while trying to set up an AuthorizationCodeFlow without scopes.

According to here: https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow

> If no scopes are specified, authorization will be granted only to access publicly available information: that is, only information normally visible in the Spotify desktop, web, and mobile players.

However currently[ AuthorizationCodeFlow.valid()](https://github.com/HuiiBuh/AsyncSpotify/blob/ac75c6ad0431413841e521fde821240d41813d01/src/async_spotify/authentification/authorization_flows/authorization_code_flow.py#L57) enforces scopes to be non-empty.

**Comment by HuiiBuh** [comment]
You are right. 
In this case the scopes should not be checked.
I will remove this in the future. If you want to create a pull request, I would be happy to merge it
