### ISSUE TITLE
New version 0.4.2 does not contain pull request 

### ISSUE THREAD

**Issue by wackazong** [HuiiBuh/AsyncSpotify#41]
Hi there, I saw you merged my pull request in commit c52a9da60d5963512bb256ea9f4d243d7f1b6844. But the PyPI version 0.4.2 still contains the old code. Any chance you can make a new release? Thanks!

**Comment by HuiiBuh** [comment]
Sry, just published it
https://pypi.org/project/async-spotify/0.4.3/
